PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX ls: <http://www.laces.tech/publication/ns/semmtech/live/laces/schema/shapes/>
PREFIX lbm: <http://www.laces.tech/publication/ns/semmtech/live/laces/schema/blueprint-manager/>
PREFIX otl: <http://www.laces.tech/publication/ns/semmtech/live/laces/schema/otl-manager/>

SELECT DISTINCT ?aspectName ?qualificationName ?nQuals
WHERE {
  ?hasAspect otl:rel-Relation-toRole ?aspectRole .
  ?hasAspect otl:rel-Relation-to ?aspect .
  
  ?aspect otl:attr-Conceptual-name ?aspectName .
  
  ?aspectRole otl:rel-RoleOfAspect-PossessedAspect-isQualifiedAs-Qualification ?qualification  .
  
  ?qualification otl:attr-Conceptual-name ?qualificationName .
  
  FILTER (CONTAINS(?qualificationName, ",")) .
  
  BIND (STRLEN(REPLACE(?qualificationName, "[^,]", "")) AS ?nQuals) .  
}
