PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX nen2660: <https://w3id.org/nen2660/def#>
PREFIX imv: <https://data.crow.nl/imv/def/>

SELECT DISTINCT ?fysiekePlaatUri ?fysiekePlaatNameNL ?fysiekePlaatNameEN # ?vnvf
WHERE {
  ?fysiekePlaatUri a owl:Class .
  ?fysiekePlaatUri rdfs:subClassOf imv:FysiekePlaat .
  OPTIONAL {
    ?fysiekePlaatUri skos:prefLabel ?fysiekePlaatNameNL .
    FILTER (LANG(?fysiekePlaatNameNL) = "nl") .
  }
  OPTIONAL {
    ?fysiekePlaatUri skos:altLabel ?fysiekePlaatNameEN .
    FILTER (LANG(?fysiekePlaatNameEN) = "en") .
  }
  
  ?fysiekePlaatUri nen2660:isDescribedBy ?vnvf .
  FILTER (contains(str(?vnvf), "https://vnvf.nl/product/vnvf-bordenboek/") )
}