PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX vb: <https://data.crow.nl/imv/def/>

SELECT DISTINCT ?iconURI ?iconName ?iconDefinition ?svg

WHERE {
    ?iconURI a owl:Class .
    ?iconURI rdfs:subClassOf vb:Icoon .
    ?iconURI skos:prefLabel ?iconName .
    FILTER (LANG(?iconName) = "nl") .
    ?iconURI skos:definition ?iconDefinition .
    FILTER (LANG(?iconDefinition) = "nl") .
    ?iconURI rdfs:seeAlso ?svg .
    FILTER (STRSTARTS(str(?svg), "https://raw.githubusercontent.com/ndwnu/qgis-verkeersborden-style/")) .
}