PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>
PREFIX nen2660: <https://w3id.org/nen2660/def#>
PREFIX imv: <https://data.crow.nl/imv/def/>

# Query to retrieve plates from Staandard Verkeersborden publication 

SELECT DISTINCT ?URI ?name ?definition ?svgImage
WHERE {
  ?URI rdfs:subClassOf imv:FysiekePlaat .
  OPTIONAL {
    ?URI skos:prefLabel ?name .
    FILTER (LANG(?name) = "nl") .
  }
  OPTIONAL {
    ?URI skos:definition ?definition .
    FILTER (LANG(?definition) = "nl") .
  }
  OPTIONAL {
    ?URI nen2660:isDescribedBy ?svgImage .
	FILTER (contains(str(?svgImage), "https://raw.githubusercontent.com/nl-digigo/NLCS/") )
  }
}