PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX sh: <http://www.w3.org/ns/shacl#>

SELECT DISTINCT ?termUri ?termNameNL ?termNameEN ?termDefinitionNL ?termDefinitionEN ?parentTermUri ?collectionUri ?collectionNameNL ?collectionNameEN ?collectionDefinitionNL ?collectionDefinitionEN
WHERE {
  ?termUri a skos:Concept .
  ?termUri skos:prefLabel ?termNameNL .
  FILTER ( LANG(?termNameNL) = "nl" ) .
  ?termUri skos:prefLabel ?termNameEN .
  FILTER ( LANG(?termNameEN) = "en" ) .
  OPTIONAL {
    ?termUri skos:definition ?termDefinitionNL .
  	FILTER ( LANG(?termDefinitionNL) = "nl" ) .
  	?termUri skos:definition ?termDefinitionEN .
    FILTER ( LANG(?termDefinitionEN) = "en" ) .
  }
  OPTIONAL { ?termUri skos:broader ?parentTermUri . }
  OPTIONAL {
    ?collectionUri a skos:Collection .
    ?collectionUri skos:member ?termUri .
  	?collectionUri skos:prefLabel ?collectionNameNL .
  	FILTER ( LANG(?collectionNameNL) = "nl" ) .
  	?collectionUri skos:prefLabel ?collectionNameEN .
  	FILTER ( LANG(?collectionNameEN) = "en" ) .
  	?collectionUri skos:definition ?collectionDefinitionNL .
  	FILTER ( LANG(?collectionDefinitionNL) = "nl" ) .
  	?collectionUri skos:definition ?collectionDefinitionEN .
  	FILTER ( LANG(?collectionDefinitionEN) = "en" ) .
  }
}